package tool.rental.presentation;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import tool.rental.domain.controllers.FriendsRankController;
import tool.rental.utils.PresentationFrame;
import tool.rental.utils.TableConfigurator;
import tool.rental.utils.ToastError;

import javax.swing.JComponent;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import java.awt.Color;
import java.awt.Insets;
import java.util.List;

/**
 * Frame for displaying the ranking of friends based on their rental activity.
 * Extends PresentationFrame and initializes the UI components and table setup.
 */
public class FriendsRankFrame extends PresentationFrame {

    // Controller for handling the ranking logic
    private final FriendsRankController controller = new FriendsRankController(this);

    // UI Components
    private JTable friendsTable;
    private JScrollPane JScrollPanel;
    private JPanel MainPanel;
    private final TableConfigurator tableConfigurator;

    /**
     * Constructs the friends ranking frame and initializes components.
     *
     * @throws ToastError if there is an error during initialization
     */
    public FriendsRankFrame() throws ToastError {
        this.tableConfigurator = new TableConfigurator(friendsTable);
        setupPageLayout();
        setMainPanel();
        setupTable();
    }

    /**
     * Configures the frame layout and properties.
     */
    private void setupPageLayout() {
        setTitle("Rank de amigos");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setSize(this.userScreen.widthFraction(40), this.userScreen.heightFraction(40));
        setLocationRelativeTo(null);
    }

    /**
     * Sets the main panel for the frame.
     */
    private void setMainPanel() {
        setContentPane(this.MainPanel);
    }

    /**
     * Sets up the friends table with column headers and loads the initial data.
     *
     * @throws ToastError if there is an error during the setup or data loading
     */
    public void setupTable() throws ToastError {
        String[] columns = {
                "Posição",
                "Nome",
                "Identidade",
                "Ferramentas atualmente emprestadas",
                "Total de ferramentas emprestadas"
        };
        tableConfigurator.setup(columns, null);
        this.loadData();
    }

    /**
     * Loads data into the friends table.
     *
     * @throws ToastError if there is an error during data loading
     */
    private void loadData() throws ToastError {
        List<String[]> summary = this.controller.getRentalSummary();
        tableConfigurator.insertRows(summary, true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        MainPanel = new JPanel();
        MainPanel.setLayout(new GridLayoutManager(1, 1, new Insets(50, 25, 50, 25), -1, -1));
        MainPanel.setBackground(new Color(-14539224));
        MainPanel.setEnabled(true);
        JScrollPanel = new JScrollPane();
        JScrollPanel.setBackground(new Color(-14408668));
        MainPanel.add(JScrollPanel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        friendsTable = new JTable();
        friendsTable.setForeground(new Color(-15527649));
        friendsTable.setSelectionForeground(new Color(-4649));
        friendsTable.setShowVerticalLines(true);
        JScrollPanel.setViewportView(friendsTable);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return MainPanel;
    }

}
